openapi: 3.0.1

servers:
  # Added by API Auto Mocking Plugin
  - description: localhost (what is this for?)
    url: https://localhost:44377/api/v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/peterjochum/traffic-jam_api/1.0.0

info:
  title: Traffic Jam API
  description: API to manage traffic jams
  version: 1.0.0

paths:
  # TODO: Add a search/aggregation by area, it has to
  # be done by the backend sooner or later
  /trafficjam:
    get:
      summary: Get all traffic jams
      # TODO: Remove this. Nobody needs a list of all traffic jams
      operationId: getAllTrafficJams
      responses:
        "200":
          description: "OK"
    post:
      summary: Create a new traffic jam report
      operationId: addTrafficJam
      requestBody:
        $ref: "#/components/requestBodies/TrafficJam"
      responses:
        "400":
          $ref: "#/components/responses/TrafficJamBadRequest"
    put:
      summary: Update traffic jam report
      operationId: putTrafficJam
      requestBody:
        $ref: "#/components/requestBodies/TrafficJam"
      responses:
        "404":
          $ref: "#/components/responses/TrafficJamNotFound"
  "/trafficjam/{id}":
    get:
      summary: Return traffic jam by {id}
      operationId: getTrafficJam
      parameters:
        - name: id
          in: path
          description: ID of traffic jam to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "404":
          $ref: "#/components/responses/TrafficJamNotFound"
    delete:
      summary: delete traffic jam with {id}
      operationId: deleteTrafficJam
      parameters:
        - name: id
          in: path
          description: ID of the traffic jam to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "404":
          $ref: "#/components/responses/TrafficJamNotFound"

components:
  schemas:
    TrafficJam:
      type: object
      required:
        - id
        - longitude
        - latitude
        - durationInSeconds
      properties:
        id:
          type: integer
          format: int64
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        durationInSeconds:
          type: integer
          format: int32
  requestBodies:
    TrafficJam:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TrafficJam"
        application/xml:
          schema:
            $ref: "#/components/schemas/TrafficJam"
      description: Traffic jam that needs to be added to the store
      required: true
  responses:
    TrafficJamNotFound:
      description: traffic jam was not found
    TrafficJamBadRequest:
      description: malformed request - included all required fields?
