name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: default
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -coverprofile c.out -v ./...

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: 'linux/amd64, darwin/amd64, windows/amd64'
        package: ''
        name: 'traffic-jam-api'
        compress: 'true'
        dest: 'dist'
